services:
  db:
    image: postgres:16
    container_name: mapapp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mapapp
    ports:
      - "5435:5432"
    volumes:
      - mapapp_data:/var/lib/postgresql/data

volumes:
  mapapp_data:
